name: Generate Sources HTML

on:
  push:
    branches:
      - main # Change this if your default branch is named 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run compilation script
        run: python generate_sources.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sources.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update sources.html"
          git push